version: '3.8'
services:
  zookeeper:
    container_name: etl-zookeeper
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: etl-kafka-broker
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9029:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  postgresql:
    container_name: etl-postgres
    image: postgres:latest
    environment:
      POSTGRAS_USER: igliballa
      POSTGRES_PASSWORD: password
      PGDATA: data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5434"
    networks:
      - postgres

  mongodb:
    container_name: etl-mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=igliballa
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/mongodb
    networks:
      - mongo
    restart: unless-stopped

volumes:
  postgres:
  mongo:

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge