version: '3.8'
services:
  zookeeper:
    container_name: etl-zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: etl-kafka-broker
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9029:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgresql:
    container_name: etl-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: etl
      POSTGRES_USER: igliballa
      POSTGRES_PASSWORD: password
      PGDATA: data/postgres
    volumes:
      - postgresql:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgresql

  mongodb:
    container_name: etl-mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=igliballa
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/mongodb
    networks:
      - mongo
    restart: unless-stopped

volumes:
  postgresql:
  mongo:

networks:
  postgresql:
    driver: bridge
  mongo:
    driver: bridge