server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/etl
    username: igliballa
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  data:
    mongodb:
      database: etl
      port: 27017
      host: localhost
