spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/etl
    username: igliballa
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      database: etl
      port: 27017
      host: localhost